name: image_picker
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
description: Dart wrapper for native image picker
homepage: https://github.com/flutter/image_picker
environment:
  sdk: '>=1.9.0 <2.0.0'
